version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    parameters:
      project:
        description: What project to build
        type: string
      project_dir:
        description: Project's parent directory
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run:
          environment:
            PROJECT: << parameters.project >>
            PROJECT_DIR: << parameters.project_dir >>
          command: docker build -t blackstockc/$PROJECT $PROJECT_DIR
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t blackstockc/react-test -f ./projects/client/Dockerfile.dev ./projects/client
          docker run blackstockc/react-test npm test -- --coverage
  deploy:
    docker:
      - image: circleci/node
    steps:
      - run:
          name: Install Now CLI
          command: sudo npm install --global --unsafe-perm now
      - deploy:
          name: Deploy & Alias
          command: |
            cd ./projects/client 
            now --token $ZEIT_TOKEN
            now --token $ZEIT_TOKEN alias

workflows:
  version: 2
  Build and Test:
    jobs:
      - build:
          name: Build Client
          project: multi-client
          project_dir: ./projects/client
      - build:
          name: Build Server
          project: multi-server
          project_dir: ./projects/server
      - build:
          name: Build Worker
          project: multi-worker
          project_dir: ./projects/worker
      - build:
          name: Build Nginx
          project: multi-nginx
          project_dir: ./nginx
  Deploy:
    jobs:
      - deploy:
          name: Deploy Client
