version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    parameters:
      project:
        description: What project to build
        type: string
      project_dir:
        description: Project's parent directory
        type: string
    steps:
      - checkout
      - run:
          environment:
            PROJECT: << parameters.project >>
            PROJECT_DIR: << parameters.project_dir >>
          command: docker build -t blackstockc/$PROJECT $PROJECT_DIR
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t blackstockc/react-test -f ./projects/client/Dockerfile.dev ./projects/client
          docker run blackstockc/react-test npm test -- --coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          project: multi-client
          project_dir: './projects/client'
