version: 2
jobs:
  build:
    docker:
      - image: circleci/<language>:<version TAG>
    steps:
      - checkout
      - run: <command>
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t blackstockc/react-test -f ./projects/client/Dockerfile.dev ./projects/client
          docker run blackstockc/react-test npm test -- --coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
