version: 2
jobs:
  build:
    docker:
      - image: circleci/node
    parameters:
      name:
        description: Which project to build docker image for.
        type: string
        default: dev
      dir:
        description: Which project to build docker image for.
        type: string
        default: ./
    steps:
      - checkout
      - run: |
          docker build -t blackstockc/<< parameters.name >> << parameters.dir >>
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t blackstockc/react-test -f ./projects/client/Dockerfile.dev ./projects/client
          docker run blackstockc/react-test npm test -- --coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build:
          name: multi-client
          dir: ./projects/client
