version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node
    parameters:
      project:
        description: What project to build
        type: string
      project_dir:
        description: Project's parent directory
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run:
          environment:
            PROJECT: << parameters.project >>
            PROJECT_DIR: << parameters.project_dir >>
          command: docker build -t blackstockc/$PROJECT $PROJECT_DIR
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          docker build -t blackstockc/react-test -f ./projects/client/Dockerfile.dev ./projects/client
          docker run blackstockc/react-test npm test -- --coverage
  deploy:
    docker:
      - image: circleci/node
    parameters:
      alias:
        description: Env stage of project
        type: string
        default: -${CIRCLE_BRANCH}
      project_dir:
        description: Project's parent directory
        type: string
    steps:
      - checkout
      - run:
          name: Install Now CLI
          command: sudo npm install --global --unsafe-perm now
      - deploy:
          name: Deploy & Alias
          environment:
            PROJECT_DIR: << parameters.project_dir >>
          command: |
            cd $PROJECT_DIR
            now --token $ZEIT_TOKEN --public
            now --token $ZEIT_TOKEN alias << parameters.alias >>

workflows:
  version: 2
  Deploy:
    jobs:
      - deploy:
          name: Deploy Client
          project_dir: ./projects/client
          alias: fib-ui-${CIRCLE_BRANCH}
          filters:
            branches:
              ignore:
                - master
                - develop
      - deploy:
          name: Deploy Server
          project_dir: ./projects/server
          alias: fib-api-${CIRCLE_BRANCH}
          filters:
            branches:
              ignore:
                - master
                - develop
