# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

executors:
  node:
    docker:
      - image: circleci/node:10
jobs:
  test:
    description: Run tests
    executor: node
    steps:
      - checkout
      - run: docker build -t blackstockc/react-test -f ./projects/client/Dockerfile.dev ./projects/client
      - run:
          name: Run tests
          command: docker run blackstockc/react-test npm test -- --coverage

workflows:
  version: 2
  Build and Deploy:
    jobs:
      - test:
          name: test
